#!/usr/bin/env python3
"""Inject `<!-- kg:begin -->...<!-- kg:end -->` blocks into every wiki page.

The block lists typed in/out edges, grouped by relation. Always regenerated
from kg/ — never hand-edit the block. The .gitattributes file marks it as
non-diffable.

Run after `tools/build_kg.py`. Idempotent.
"""
from __future__ import annotations

import argparse
import json
import re
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]

KG_BEGIN = "<!-- kg:begin -->"
KG_END = "<!-- kg:end -->"

# Group similar relations together for display.
RELATION_GROUPS = [
    ("Uses", ["uses", "trained_on", "requires"]),
    ("Applied in / Succeeded in", ["applied_in", "succeeded_in"]),
    ("Failed in / Caused", ["failed_in", "caused"]),
    ("Prevents", ["prevents"]),
    ("Compared / Improves on", ["improves_on", "supersedes", "compared_to"]),
    ("Hosted by / Evaluated by", ["hosted_by", "evaluated_by", "measured_with"]),
    ("Part of / Instance of", ["part_of", "instance_of"]),
    ("Authored / Affiliated", ["authored_by", "affiliated_with", "team_members"]),
    ("Cites / Mentioned in", ["cites", "mentioned_in"]),
    ("Works with", ["works_with"]),
    ("Related", ["related_to"]),
]

INVERSE_LABELS = {
    "uses": "used by",
    "applied_in": "applied here:",  # node is itself a competition; show what was applied
    "evaluated_by": "evaluates",
    "hosted_by": "hosts",
    "succeeded_in": "successes here",
    "failed_in": "failures here",
    "caused": "caused by",
    "prevents": "prevented by",
    "supersedes": "superseded by",
    "improves_on": "improved by",
    "part_of": "contains",
    "instance_of": "instances",
    "trained_on": "trains",
    "team_members": "member of",
    "cites": "cited by",
    "mentioned_in": "mentions",
    "authored_by": "author of",
    "affiliated_with": "affiliates",
    "requires": "required by",
    "works_with": "works with",
    "compared_to": "compared with",
    "related_to": "related to",
}


def render_block(node_id: str, nodes: dict[str, dict], outgoing: list[dict],
                  incoming: list[dict]) -> str:
    """Render the markdown KG block for one node."""
    lines: list[str] = [KG_BEGIN, "<!-- This block is auto-generated by tools/inject_kg_blocks.py — do not hand-edit -->",
                        "## Knowledge Graph",
                        ""]

    # Group outgoing edges by relation group
    out_by_group: dict[str, list[dict]] = defaultdict(list)
    for e in outgoing:
        for label, rels in RELATION_GROUPS:
            if e["relation"] in rels:
                out_by_group[label].append(e)
                break

    if outgoing:
        lines.append("**Outgoing:**")
        for label, _ in RELATION_GROUPS:
            es = out_by_group.get(label, [])
            if not es:
                continue
            for e in sorted(es, key=lambda x: x["target"]):
                tgt_node = nodes.get(e["target"])
                title = tgt_node.get("title", e["target"]) if tgt_node else e["target"]
                wp = tgt_node.get("wiki_path", "") if tgt_node else ""
                if wp.startswith("wiki/"):
                    link = f"[[{wp[len('wiki/'):].replace('.md','')}|{title}]]"
                else:
                    link = f"`{e['target']}` ({title})"
                lines.append(f"- _{e['relation']}_ → {link}")
        lines.append("")

    if incoming:
        lines.append("**Incoming:**")
        in_by_group: dict[str, list[dict]] = defaultdict(list)
        for e in incoming:
            for label, rels in RELATION_GROUPS:
                if e["relation"] in rels:
                    in_by_group[label].append(e)
                    break
        for label, _ in RELATION_GROUPS:
            es = in_by_group.get(label, [])
            if not es:
                continue
            for e in sorted(es, key=lambda x: x["source"]):
                src_node = nodes.get(e["source"])
                title = src_node.get("title", e["source"]) if src_node else e["source"]
                wp = src_node.get("wiki_path", "") if src_node else ""
                if wp.startswith("wiki/"):
                    link = f"[[{wp[len('wiki/'):].replace('.md','')}|{title}]]"
                else:
                    link = f"`{e['source']}` ({title})"
                lines.append(f"- {link} _{e['relation']}_ → here")
        lines.append("")

    if not outgoing and not incoming:
        lines.append("_No relationships extracted yet._")
        lines.append("")

    lines.append(KG_END)
    return "\n".join(lines) + "\n"


def upsert_block(content: str, block: str) -> str:
    """Add or replace the KG block at end of file."""
    pattern = re.compile(re.escape(KG_BEGIN) + r".*?" + re.escape(KG_END) + r"\n?",
                          re.DOTALL)
    if pattern.search(content):
        return pattern.sub(block, content)
    if not content.endswith("\n"):
        content += "\n"
    return content + "\n" + block


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--kg", default=str(REPO / "kg"))
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    kg_root = Path(args.kg)
    nodes: dict[str, dict] = {}
    for p in (kg_root / "nodes").rglob("*.json"):
        n = json.loads(p.read_text())
        nodes[n["id"]] = n

    outgoing: dict[str, list[dict]] = defaultdict(list)
    incoming: dict[str, list[dict]] = defaultdict(list)
    for line in (kg_root / "edges.jsonl").read_text().splitlines():
        if not line.strip():
            continue
        e = json.loads(line)
        outgoing[e["source"]].append(e)
        incoming[e["target"]].append(e)

    # Group nodes by wiki_path. For each path, pick the "primary" node — the one
    # whose slug matches the file stem (e.g. competitions/march-mania-2026.md →
    # competition:march-mania-2026, NOT the submissions that share the path).
    by_path: dict[str, list[dict]] = defaultdict(list)
    for n in nodes.values():
        wp = n.get("wiki_path", "")
        if wp.startswith("wiki/"):
            by_path[wp].append(n)

    updated = 0
    skipped = 0
    for wp, candidates in by_path.items():
        page_path = REPO / wp
        if not page_path.exists():
            skipped += 1
            continue
        stem = Path(wp).stem
        primary = next((n for n in candidates if n["slug"] == stem), candidates[0])
        nid = primary["id"]
        block = render_block(nid, nodes, outgoing.get(nid, []), incoming.get(nid, []))
        content = page_path.read_text(encoding="utf-8")
        new = upsert_block(content, block)
        if new == content:
            continue
        if not args.dry_run:
            page_path.write_text(new, encoding="utf-8")
        updated += 1

    print(f"{'would update' if args.dry_run else 'updated'}: {updated} pages, {skipped} skipped")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
