#!/usr/bin/env python3
"""Regenerate wiki/index.md from kg/indexes/by-category.json + node summaries.

Preserves the existing markdown table format so casual readers see no change.
"""
from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]


TYPE_ORDER = [
    ("Meta", ["synthesis"]),
    ("Competitions", ["competition"]),
    ("Submissions", ["submission"]),
    ("Strategies", ["strategy"]),
    ("Techniques", ["technique"]),
    ("Patterns", ["pattern"]),
    ("Concepts", ["concept"]),
    ("Mistakes", ["mistake"]),
    ("People", ["person"]),
    ("Libraries", ["library"]),
    ("Models", ["model"]),
    ("API Services", ["api_service"]),
    ("Organizations", ["organization"]),
    ("Tools", ["tool"]),
    ("Comparisons", ["comparison"]),
    ("Datasets", ["dataset"]),
    ("Features", ["feature"]),
    ("Task Types", ["task_type"]),
    ("Metrics", ["metric"]),
    ("Papers", ["paper"]),
    ("Sources (raw/)", ["source"]),
]

# Cap source listing
MAX_SOURCES = 20


def render_table(rows: list[tuple[str, str, str, str]]) -> list[str]:
    out = ["| Page | Tags | Status | Summary |", "|------|------|--------|---------|"]
    for link, tags, status, summary in rows:
        out.append(f"| {link} | {tags} | {status} | {summary} |")
    return out


def to_link(node: dict) -> str:
    wp = node.get("wiki_path", "")
    title = node.get("title", node["id"])
    if wp.startswith("wiki/"):
        return f"[[{wp[len('wiki/'):].replace('.md', '')}]]"
    return f"`{node['id']}`"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--kg", default=str(REPO / "kg"))
    ap.add_argument("--out", default=str(REPO / "wiki" / "index.md"))
    args = ap.parse_args()

    kg_root = Path(args.kg)
    nodes: dict[str, dict] = {}
    for p in (kg_root / "nodes").rglob("*.json"):
        n = json.loads(p.read_text())
        nodes[n["id"]] = n

    # Group strictly by node type
    by_type: dict[str, list[dict]] = defaultdict(list)
    for n in nodes.values():
        by_type[n["type"]].append(n)

    lines = [
        "---",
        "id: meta:wiki-index",
        "type: synthesis",
        "title: Wiki Index",
        "slug: wiki-index",
        "aliases: []",
        "tags: [meta]",
        "status: active",
        "date: " + sorted({n.get("updated", "") for n in nodes.values()})[-1],
        "source_count: 0",
        "---",
        "",
        "<!-- Auto-generated by tools/render_index.py from kg/indexes/by-category.json. Do not hand-edit. -->",
        "",
        "# Wiki Index",
        "",
        f"Knowledge graph index — **{len(nodes)} nodes** across **{len({n['type'] for n in nodes.values()})} types**.",
        "Run `python tools/render_index.py` after a build to regenerate.",
        "",
        "---",
    ]

    for label, types in TYPE_ORDER:
        rows: list[tuple[str, str, str, str]] = []
        for tname in types:
            for n in sorted(by_type.get(tname, []), key=lambda x: x.get("title", x["id"]).lower()):
                if tname == "source" and len(rows) >= MAX_SOURCES:
                    break
                tags = ", ".join((n.get("tags") or [])[:5])
                summary = (n.get("summary") or "").replace("\n", " ").replace("|", "\\|")[:160]
                rows.append((to_link(n), tags, n.get("status", ""), summary))
        if not rows:
            continue
        lines.append("")
        lines.append(f"## {label}")
        lines.append("")
        if label == "Sources (raw/)" and len(by_type.get("source", [])) > MAX_SOURCES:
            lines.append(f"_Showing first {MAX_SOURCES} of {len(by_type['source'])} sources. See `kg/nodes/source/` for the full list._")
            lines.append("")
        lines.extend(render_table(rows))
        lines.append("")
        lines.append("---")

    Path(args.out).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {args.out} ({len(nodes)} nodes indexed)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
